<html lang="en">
	<body>
    	<form action="/library/add" method="post">
    		<label for="book_name">Book Name</label>
			<input type="text" name="book_name"/>
			<br>
			<label for="author">Author</label>
			<input type="text" name="author"/>
			<br>
			<label for="year_published">Year Published</label>
			<input type="text" name="year_published"/>
			<br>
			<button type="submit">Add</button>
		</form>  
					
	</body>
</html>